### ISSUE TITLE
Sign app bundle

### ISSUE THREAD

**Issue by krono** [HPI-SWA-Lab/RSqueak-App#3]
Apple .app's do not like things besides the Contents folder

**Comment by fniephaus** [comment]
Squeak All-in-One does the same. What exactly do you mean? I didn't find any info on this [here](https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html).

**Comment by krono** [comment]
It's about signing, actually

http://forum.world.st/Re-Newbies-Running-Squeak-on-Mac-OS-X-fails-due-to-damaged-file-tp4780481p4781328.html

**Comment by fniephaus** [comment]
I've updated the issue and postpone it until we actually want/need to sign the app bundle...

**Comment by krono** [comment]
ack
